### ISSUE TITLE
Importing error to these fields: Error from API Contact create: Found more than one Organisation with same Name."

### ISSUE THREAD

**Issue by andyburnsco** [mattwire/uk.co.mjwconsult.optinfields#1]
This is a much needed extension! Excited to implement but I am getting this error upon import: https://pastebin.com/wHtKWjci.

I have been able to do a sample import of 1 contact to the new opt in fields. I also did an import to a regular custom field that I had intended to migrate over from to your calculated custom fields. I was able to import on our dev site which is not an exact copy.

The difference is on production we have contact imported as individuals and (e.g. Burns, Andy) and as organization contact subtype contact like Andy Burns if they fit that type. That makes sense given this error: 'Found more than one Organisation with same Name.' However, on import we specify the contact type we are importing and in this case it is individuals.

Thoughts on how to avoid this?

**Comment by andyburnsco** [comment]
I attempted to change an org contact with my name to something that did not match and still get the same error. Perhaps setting the custom field set to be used for 'individual' contact type may fix?

**Comment by mattwire** [comment]
Hi @andyburnsco Thanks for using and reporting this.  I can't quite see what is going on from the backtrace alone.  But I suspect the hook in optinfields should be ignoring "Organisation" contact types - is entity ID=20 an organisation?
If you'd like me to look into this further you can also reach me by the email on my github profile.

**Comment by andyburnsco** [comment]
ID 20 is an individual. I'll message you separately.

**Comment by mattwire** [comment]
Now moved to https://lab.civicrm.org/extensions/optinfields - please re-open there if still an issue
